Sign release versions and fix release build error
Error: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeFreeReleaseResources'.
Error was caused by an png file which was used as a mock when creating layouts